---
title: "Scrapeo"
author: "Juan Vargas"
date: "14/9/2021"
output: html_document
---

```{r}
library(tidyverse)
library(rvest)
```

#Mostramos la variacion diaria del dolar en relacion a los pesos argentinos desde la web


```{r}
dolar_argentina <- read_html("https://www.cronista.com/MercadosOnline/dolar.html") 
```


```{r}
variacion_dolar <- dolar_argentina %>% 
  html_elements("a") %>% 
  html_text()
```


#Mostramos la informacion desde la web sobre los contagios de Covid-19 en Ciudad de Buenos Aires

```{r}
covid_CABA <- read_html ("https://es.wikipedia.org/wiki/Pandemia_de_COVID-19_en_la_Ciudad_Aut%C3%B3noma_de_Buenos_Aires")
```


```{r}
contagios <- covid_CABA %>% 
  html_nodes( xpath = '//*[@id="mw-content-text"]/div[1]/div[2]/table/tbody/tr/td[1]/div/table')%>% 
  html_table()
```

#Guardamos los datos en una tabla

```{r}
contagios_tabla <- contagios[[1]]
```



#Desde la pagina de Argentina Aeropuertos 2000 (AA200) mostramos los arribos y partidas para el Aeropuerto de Ezeiza (EZE)

```{r}
AA2000 <- read_html("https://www.aa2000.com.ar/")
```




```{r}
VUELOS <- AA2000 %>% 
  html_nodes( xpath = '//*[@id="UpdatePanel2"]')%>% 
  html_table()
```

#Guardamos los datos en una tabla

```{r}
tabla_AA200 <- VUELOS[[1]] 
```

